.TH UNDANGLE 1 "2011 June 21" Linux "Linux"

.SH NAME
undangle \- program for automatically recursing a directory and removing
any broken symlinks found.

.SH SYNOPSIS
undangle [option] directory


.SH DESCRIPTION
This manual page explains the
.B undangle
program. 
.PP
\fBautolink\fP is for recursively traversing the sub directories of the
input directory and removing any broken symlinks found.

.SH OPTIONS
-h - outputs a help message.

.SH EXAMPLE
undangle path_to_traverse

.SH "SEE ALSO"
man autolink (1)
 
.SH AUTHOR
Robert L Parker <rlp1938@gmail.com>

